image: hub.c.163.com/qingzhou/maven-tomcat:8-jdk8-3
variables:
  # Please edit to your GitLab project
  CI_REGISTRY_IMAGE: ${CI_REGISTRY}/qingzhou/nsf-api-plane-server
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2  
  DOCKER_HOST: tcp://docker:2375/

stages:
  - build
  - buildImage
  

before_script:
  - export MAVEN_HOME=/usr/local/bin/apache-maven-3.6.3

job_build:
  stage: build
  script:
    - $MAVEN_HOME/bin/mvn clean
    - echo "now stage is 1-build"  
  tags:
    - qz-gitlab-runner

job_buildImage:
    stage: buildImage
    image: docker:stable
    services:
      - docker:dind
    before_script:
      - echo "Qingzhou4321"| docker login -u "staff.qingzhou@service.netease.com" --password-stdin hub.c.163.com
    
    cache:
     paths:
      - /builds/qingzhou/yx-gateway-api-plane/nsf-api-plane-server

    script:
      - echo "Building image - hub.c.163.com/qingzhou/nsf-api-plane-server:latest"
      - cd /builds/qingzhou/yx-gateway-api-plane/nsf-api-plane-server/
      - docker image build --force-rm --no-cache -t $CI_REGISTRY_IMAGE:latest .
      - docker image push $CI_REGISTRY_IMAGE:latest
    only:
      - release-1.1
      
    tags:
      - qz-gitlab-runner






