---
apiVersion: v1
kind: Namespace
metadata:
  name: qz
  labels:
    istio-injection: enabled
---
### harbor imagePullSecret
apiVersion: v1
data:
  .dockerconfigjson:  eyJhdXRocyI6eyJodWIuYy4xNjMuY29tL3Fpbmd6aG91Ijp7InVzZXJuYW1lIjoic3RhZmYucWluZ3pob3VAc2VydmljZS5uZXRlYXNlLmNvbSIsInBhc3N3b3JkIjoiUWluZ3pob3U0MzIxIiwiZW1haWwiOiJzdGFmZi5xaW5nemhvdUBzZXJ2aWNlLm5ldGVhc2UuY29tIiwiYXV0aCI6ImMzUmhabVl1Y1dsdVozcG9iM1ZBYzJWeWRtbGpaUzV1WlhSbFlYTmxMbU52YlRwUmFXNW5lbWh2ZFRRek1qRT0ifX19
kind: Secret
metadata:
  name: qingzhou-secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qz-egress
  namespace: istio-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx
  namespace: istio-system
data:
  proxy.conf: |-
    server {
       listen 80;
        location / {
           proxy_pass http://10.177.1.3:8090;
           proxy_set_header Host $host;
           proxy_set_header User-Agent $http_user_agent;
       }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qz-egress
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qz-egress
  template:
    metadata:
      labels:
        app: qz-egress
    spec:
      serviceAccountName: qz-egress
      containers:
      - image: nginx:1.17
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 500m
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx
      imagePullSecrets:
      - name: "qingzhou-secret"
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: qz-egress
  namespace: istio-system
spec:
  targets:
  - name: qz-egress
  peers:
  - mtls:
      mode: STRICT
---
apiVersion: v1
kind: Service
metadata:
  name: qz-egress
  namespace: istio-system
  labels:
    app: qz-egress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: qz-egress
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: qz-egress
  namespace: istio-system
spec:
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  host: qz-egress
