#轻舟API会对这个资源进行操作, 所以只有不存在时才创建
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    services:
    - qz-egress.istio-system.svc.cluster.local